### ISSUE TITLE
Service got stuck somewhere - values were no longer updated

### ISSUE THREAD

**Issue by tm-107** [AchimKre/venus.dbus-tasmota-smartmeter#2]
I don't know exactly where the problem is, but I've had it twice now that the script or service got stuck somewhere and the values were no longer updated. The result was that the battery was drained at maximum power in a very short time.

That's why I wrote the following script, which I run every minute via crontab. Maybe it will help someone else...

[check_tasmota_smartmeter.txt](https://github.com/AchimKre/venus.dbus-tasmota-smartmeter/files/14922374/check_tasmota_smartmeter.txt)

The script checks the performance transmitted by Tasmota. If this remains unchanged for 5 minutes, the service will be restarted.
The time could also be chosen shorter, since the value - at least for me - actually changes nearly every second. But I found 5 minutes to be a good compromise.

The two variables (performance and the minute counter) are stored in separate files (power_old and power_cnt) in /run.
The timestamp is also saved in /var/log/power_res.log with every reset.

I don't have much experience in scripting, so there are certainly a lot of points that could be improved...

**Comment by tm-107** [comment]
The same thing again, a little shorter.
This time the UpdateIndex is evaluated. Hoping that this will no longer be incremented with the error I'm experiencing.
This triggers the reset on the second run and saves a variable file.

[check_tasmota_smartmeter.txt](https://github.com/AchimKre/venus.dbus-tasmota-smartmeter/files/14950567/check_tasmota_smartmeter.txt)

**Comment by tm-107** [comment]
I may have found the cause... [Link](https://github.com/AchimKre/venus.dbus-tasmota-smartmeter/issues/3)

**Comment by AchimKre** [comment]
Hi @tm-107,

We can certainly close the topic, can't we?

Thanks!
