### ISSUE TITLE
stops working after restart

### ISSUE THREAD

**Issue by ZNicoZ** [AchimKre/venus.dbus-tasmota-smartmeter#9]
Hi,

I installed your script on a raspberry pi zero.
It works great until I restart the raspy. After restart, I have to run `ln -s /data/dbus-tasmota-smartmeter/service /service/dbus-tasmota-smartmeter` again for it to work.

It´s probably something easy for someone with linux skills - can anyone help?

I would like the script tor run automatically after a restart.

Thanks!

**Comment by AchimKre** [comment]
Hi @ZNicoZ ,

You have probably overlooked the fact that you have to add the command to rc.local. Please have a look at the documentation point 4.

Thanks!

**Comment by ZNicoZ** [comment]
yes, I did, docs are a little confusing there for a beginner. Thanks
